import Head from "next/head";
import Footer from "./footer";
import Header from "./header";

type Props = {
  children: React.ReactNode;
};

export default function Layout(props: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" href="/favicon-32x32.png" sizes="32x32" />
        <link rel="icon" href="/favicon-16x16.png" sizes="16x16" />
        <link rel="icon" href="/android-chrome-192x192" sizes="192x192" />
        <link rel="icon" href="/android-chrome-512x512" sizes="512x512" />
        <link rel="icon" href="/apple-touch-icon.png" sizes="180x180" />
        <meta name="theme-color" content="#f5d548" />
        <meta name="application-name" content="Christian Enevoldsen" />
        <meta
          name="apple-mobile-web-app-title"
          content="Christian Enevoldsen"
        />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
      </Head>

      <Header />
      <main className="relative overflow-x-clip">{props.children}</main>
      <Footer />
    </>
  );
}
